'use client';

import { motion } from 'framer-motion';
import { BellRing, Bot, Clock3, FileUp, Filter, Search, Send, ShieldCheck, Sparkles, TrendingUp, Users } from 'lucide-react';

const card = 'rounded-luxe border border-white/40 bg-white/70 backdrop-blur-xl shadow-soft';
const chartData = [{m:'Jan',revenue:124000,leads:240},{m:'Feb',revenue:138000,leads:260},{m:'Mar',revenue:150000,leads:301},{m:'Apr',revenue:169000,leads:320},{m:'May',revenue:182000,leads:372},{m:'Jun',revenue:201000,leads:390}];

const fade = { initial: { opacity: 0, y: 14 }, animate: { opacity: 1, y: 0 } };

function Shell({ title, subtitle, children }: any){return <div className="space-y-6"><div><h1 className="text-3xl md:text-4xl font-semibold tracking-tight">{title}</h1><p className="text-inkaa-muted mt-1">{subtitle}</p></div>{children}</div>}
function Kpis(){const k=[['Pipeline Value','$4.82M','+12.6%'],['Win Rate','38.4%','+4.2%'],['Active Deals','128','+18'],['NPS','71','+5']];return <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{k.map(([n,v,d])=><motion.div whileHover={{y:-3}} key={n} className={`${card} p-5`}><p className="text-sm text-inkaa-muted">{n}</p><p className="text-2xl font-semibold mt-2">{v}</p><p className="text-xs text-emerald-600 mt-1">{d}</p></motion.div>)}</div>}

export function DashboardPage(){return <Shell title="Executive Dashboard" subtitle="AI-powered CRM performance overview"><Kpis/><div className="grid xl:grid-cols-3 gap-4"><motion.div {...fade} className={`${card} p-5 xl:col-span-2 h-[360px]`}><h3 className="font-medium mb-3">Revenue Momentum</h3><div className='h-[88%] flex items-end gap-3'>{chartData.map(d=><div key={d.m} className='flex-1 text-center'><div className='rounded-t-xl bg-gradient-to-t from-red-500 to-red-300 hover:opacity-80 transition-all' style={{height:`${d.revenue/2600}px`}}></div><p className='text-xs mt-2 text-inkaa-muted'>{d.m}</p></div>)}</div></motion.div><div className={`${card} p-5`}><h3 className="font-medium mb-4">AI Insights</h3><div className="space-y-3 text-sm"><div className="p-3 rounded-2xl bg-violet-50">⚡ Enterprise leads convert 2.3x faster after call within 24h.</div><div className="p-3 rounded-2xl bg-blue-50">🎯 Recommend reallocating 18% ad spend to Northeast.</div><div className="p-3 rounded-2xl bg-emerald-50">✅ Team Delta has best close rate at 46%.</div></div></div></div></Shell>}

export function AnalyticsPage(){const funnel=[{name:'Visitors',value:9800},{name:'Leads',value:4020},{name:'SQL',value:1830},{name:'Closed',value:634}];const geo=[{name:'US',value:44},{name:'EU',value:31},{name:'APAC',value:25}];return <Shell title="Analytics Intelligence" subtitle="Revenue, funnel, productivity and geography"><Kpis/><div className="grid lg:grid-cols-2 2xl:grid-cols-3 gap-4"><div className={`${card} p-5 h-[320px]`}><h3>Revenue Chart</h3><div className='h-[90%] flex items-end gap-2'>{chartData.map(d=><div key={d.m} className='flex-1'><div className='bg-red-500/80 rounded-t-md' style={{height:`${d.revenue/2600}px`}}></div><p className='text-xs text-center mt-1'>{d.m}</p></div>)}</div></div><div className={`${card} p-5 h-[320px]`}><h3>Conversion Funnel</h3><div className='space-y-3 mt-6'>{funnel.map((f,i)=><div key={f.name} className='mx-auto rounded-xl text-center text-sm text-white py-2' style={{width:`${95-i*18}%`,background:['#FF6B6B','#FF8E72','#FFB16E','#FFD56B'][i]}}>{f.name}: {f.value}</div>)}</div></div><div className={`${card} p-5 h-[320px]`}><h3>Geographic Sales</h3><div className='mt-6 space-y-3'>{geo.map((g,i)=><div key={g.name}><div className='flex justify-between text-sm'><span>{g.name}</span><span>{g.value}%</span></div><div className='h-2 rounded bg-slate-200 mt-1'><div className='h-2 rounded' style={{width:`${g.value}%`,background:['#5B8FF9','#61DDAA','#65789B'][i]}}></div></div></div>)}</div></div><div className={`${card} p-5`}><h3>AI-generated Insights</h3><ul className='mt-3 space-y-2 text-sm'><li><Bot className='inline w-4 mr-1'/>Forecast indicates +14% Q3 ARR.</li><li><TrendingUp className='inline w-4 mr-1'/>SMB churn risk rose 3% this week.</li><li><Users className='inline w-4 mr-1'/>Best rep handoff time: 2–4 PM local.</li></ul></div><div className={`${card} p-5`}><h3>Team Productivity</h3><p className='text-sm mt-2'>127 tasks complete • 92% SLA • 4.7h avg response</p></div><div className={`${card} p-5`}><h3>Activity Timeline</h3><div className='text-sm mt-2 space-y-2'><p>10:34 Deal moved to negotiation</p><p>09:12 AI suggested follow-up cadence</p><p>08:04 Demo booked with Acme Health</p></div></div></div></Shell>}

export function LeadsPage(){return <Shell title='Leads Command Center' subtitle='Pipeline Kanban, scoring, and recommendations'><div className='flex gap-2 flex-wrap'><div className={`${card} px-3 py-2 flex items-center gap-2`}><Search className='w-4'/><span className='text-sm'>Search leads...</span></div><div className={`${card} px-3 py-2 flex items-center gap-2`}><Filter className='w-4'/>Filters</div></div><div className='grid xl:grid-cols-4 gap-4'>{['New','Contacted','Qualified','Proposal'].map((c,i)=><div key={c} className={`${card} p-4`}><h4 className='font-medium mb-2'>{c}</h4><div className='space-y-2'>{[1,2,3].map(n=><div key={n} className='rounded-2xl p-3 bg-white/80 shadow-sm hover:shadow-md transition'><p className='font-medium'>Lead {i+1}{n}</p><p className='text-xs text-inkaa-muted'>Score {72+i*6+n}</p></div>)}</div></div>)}</div><div className={`${card} p-5`}><h3>AI Recommendations</h3><p className='text-sm mt-2'>Prioritize Medcore (96 score) and run personalized outbound sequence.</p></div></Shell>}

export function MessagesPage(){return <Shell title='Messages Hub' subtitle='Customer conversations with AI summaries'><div className='grid lg:grid-cols-3 gap-4'><div className={`${card} p-4`}><h3>Inbox Categories</h3><ul className='text-sm mt-3 space-y-2'><li>Priority (12)</li><li>Deals (38)</li><li>Support (21)</li></ul></div><div className={`${card} p-4 lg:col-span-2`}><h3>Conversation</h3><div className='space-y-3 mt-4'><div className='p-3 rounded-2xl bg-blue-50 max-w-md'>Can we get enterprise SSO by June?</div><div className='p-3 rounded-2xl bg-emerald-50 max-w-md ml-auto'>Yes—implementation can start next week.</div></div><div className='mt-4 flex gap-2'><input className='flex-1 rounded-2xl border px-3 py-2' placeholder='Reply...'/><button className='rounded-2xl bg-black text-white px-4'><Send className='w-4'/></button></div><p className='text-xs mt-3 text-inkaa-muted'>AI summary: buyer asks about SSO timeline and legal review.</p></div></div></Shell>}

export function CallsPage(){return <Shell title='Calls Intelligence' subtitle='History, recordings, and sentiment'><div className='grid xl:grid-cols-3 gap-4'><div className={`${card} p-4 xl:col-span-2`}><h3>Call History</h3><table className='w-full text-sm mt-3'><tbody>{[['Acme','32m','Positive'],['Delta','18m','Neutral'],['Pulse','41m','Positive']].map(r=><tr key={r[0]} className='border-b'><td className='py-2'>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td></tr>)}</tbody></table></div><div className={`${card} p-4`}><h3>AI Call Summary</h3><p className='text-sm mt-2'>Strong interest in annual contract; objections on onboarding time.</p><p className='text-sm mt-2'>Sentiment: <span className='text-emerald-600'>82% positive</span></p></div></div></Shell>}

export function TasksPage(){return <Shell title='Tasks Orchestration' subtitle='Drag-ready team execution board'><div className='grid md:grid-cols-3 gap-4'>{['Todo','In Progress','Done'].map((c,ci)=><div key={c} className={`${card} p-4`}><h3>{c}</h3><div className='space-y-2 mt-3'>{[1,2,3].map(n=><div key={n} className='rounded-2xl bg-white/90 p-3'><p className='font-medium'>Task {ci+1}.{n}</p><p className='text-xs'>Priority: {n===1?'High':'Medium'} • Due: May {12+n}</p></div>)}</div></div>)}</div></Shell>}

export function DocumentsPage(){return <Shell title='Documents Workspace' subtitle='File management with AI extraction'><div className='grid lg:grid-cols-3 gap-4'><div className={`${card} p-4 lg:col-span-2`}><h3>Shared Files</h3><div className='space-y-2 mt-3'>{['Q2 Proposal.pdf','MSA-v12.docx','Onboarding Deck.pptx'].map(f=><div key={f} className='flex justify-between p-3 rounded-2xl bg-white/80'><span>{f}</span><span className='text-xs text-inkaa-muted'>AI summarized</span></div>)}</div></div><div className={`${card} p-4`}><h3>Upload Area</h3><div className='mt-4 rounded-2xl border-2 border-dashed p-8 text-center'><FileUp className='mx-auto'/><p className='text-sm mt-2'>Drop files to upload</p></div></div></div></Shell>}

export function CalendarPage(){return <Shell title='Calendar & Scheduling' subtitle='Meetings, events, and timeline'><div className='grid xl:grid-cols-3 gap-4'><div className={`${card} p-4 xl:col-span-2`}><h3>Timeline View</h3><div className='mt-3 space-y-2'>{['09:00 Discovery - Northstar','11:30 Demo - Acme','14:00 Renewal - Vertex'].map(e=><div key={e} className='p-3 rounded-2xl bg-white/80'>{e}</div>)}</div></div><div className={`${card} p-4`}><h3>Upcoming</h3><p className='text-sm mt-2'>7 meetings today</p><p className='text-sm'>3 events this week</p></div></div></Shell>}

export function SettingsPage(){return <Shell title='Settings' subtitle='Enterprise controls for your workspace'><div className='grid lg:grid-cols-2 gap-4'>{[['Team management',Users],['Billing',Clock3],['API integrations',Sparkles],['Notifications',BellRing],['Security',ShieldCheck]].map(([n,I]:any)=><div key={n} className={`${card} p-5 hover:shadow-glow transition`}><I className='w-5 mb-2'/><h3 className='font-medium'>{n}</h3><p className='text-sm text-inkaa-muted mt-1'>Configure {n.toLowerCase()} preferences.</p></div>)}</div></Shell>}
